hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

collect:
  year: 2024
  fpl_url: https://fantasy.premierleague.com/api/bootstrap-static/
  fpl_hist: https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/

data:
  raw: data/raw/sample.csv
  processed: data/processed/processed.csv
  final: data/final/final.csv
